# Generated by Django 3.0.5 on 2020-04-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='user_id',
            new_name='student_id',
        ),
    ]
