# Generated by Django 3.0.5 on 2020-04-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20200429_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_item',
            name='borrow_id',
        ),
        migrations.RemoveField(
            model_name='borrow_item',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Borrow_Item',
        ),
    ]
