# Generated by Django 3.0.5 on 2020-04-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0006_auto_20200429_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='borrow_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='borrow_item_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='request_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(blank=True, choices=[('01', 'อยู่ในตะกร้า'), ('02', 'รออนุมัติ'), ('03', 'ยืนยันการยืม'), ('04', 'คืนแล้ว'), ('05', 'ยกเลิก'), ('06', 'ของเสีย/หาย')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
