# Generated by Django 3.0.5 on 2020-04-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_delete_borrow'),
        ('borrow', '0008_auto_20200429_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(max_length=2)),
                ('tab_name', models.CharField(max_length=30)),
                ('tab_type', models.CharField(choices=[('dashboard', 'dashboard'), ('all', 'all')], default='all', max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(blank=True, choices=[('01', 'อยู่ในตะกร้า'), ('02', 'รออนุมัติ'), ('03', 'ยืนยันการยืม'), ('04', 'คืนแล้ว'), ('05', 'ยกเลิก'), ('06', 'ของเสีย/หาย'), ('07', 'จอง')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_borrow', models.IntegerField(blank=True, null=True)),
                ('borrow_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrow.Borrow')),
                ('borrow_item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrow.Borrow_Item')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Item')),
            ],
        ),
    ]
