# Generated by Django 3.0.5 on 2020-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='addadmin',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='addadmin',
            name='is_staff',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
