# Generated by Django 3.0.5 on 2020-04-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200429_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addadmin',
        ),
    ]
