# Generated by Django 3.0.5 on 2020-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_amount', models.IntegerField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('reserve_status', models.CharField(default='01', max_length=2)),
                ('amount_reserve', models.IntegerField(default=0)),
            ],
        ),
    ]
