# Generated by Django 3.0.5 on 2020-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200428_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='del_flag',
            field=models.BooleanField(default=False),
        ),
    ]
