# Generated by Django 3.0.5 on 2020-04-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_del_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='del_flag',
        ),
    ]
