# Generated by Django 3.0.5 on 2020-04-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_borrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
